### PR TITLE
Feature/auto backup off

### PR DESCRIPTION
**Pull request by mhmtk**

### CODE REVIEW

**Comment by leonardoxh** [comment]
Oh thats nice.

Do u still using FakeSearchView into projects?

**Comment by mhmtk** [comment]
@leonardoxh Yea I added it a while back and it's still there. I had to add a few hooks to improve it/suit it to my use case but it works! Thx btw

**Comment by leonardoxh** [comment]
@mhmtk That's interesting, should we continue developing the library ?

**Comment by leonardoxh** [comment]
Also, can you share some details of you use case of the library ? Like the application link (if it's in playstore) 

:)

**Comment by mhmtk** [comment]
Yea man sure! I'll take a look at it over the weekend and see if i can find things to improve

I've attached it to a filterable RecyclerView and use it to filter that list, nothing fancy

**Pull request merged**
